# Generated by Django 4.2.27 on 2025-12-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeholeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_name', models.CharField(max_length=50, verbose_name='匿名昵称')),
                ('anonymous_name_expires', models.DateTimeField(verbose_name='昵称过期时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否被折叠')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treehole_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='treehole.treeholecomment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '树洞评论',
                'verbose_name_plural': '树洞评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeholePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_name', models.CharField(max_length=50, verbose_name='匿名昵称')),
                ('anonymous_name_expires', models.DateTimeField(verbose_name='昵称过期时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('post_type', models.CharField(choices=[('CONFESSION', '表白'), ('COMPLAINT', '吐槽'), ('MOOD', '心情'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='帖子类型')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否被折叠')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treehole_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '树洞帖子',
                'verbose_name_plural': '树洞帖子',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeholeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='treehole.treeholecomment', verbose_name='评论')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='treehole.treeholepost', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treehole_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '树洞点赞',
                'verbose_name_plural': '树洞点赞',
            },
        ),
        migrations.AddField(
            model_name='treeholecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='treehole.treeholepost', verbose_name='帖子'),
        ),
        migrations.AddIndex(
            model_name='treeholepost',
            index=models.Index(fields=['-created_at'], name='treehole_tr_created_d7a1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='treeholepost',
            index=models.Index(fields=['author'], name='treehole_tr_author__3c1fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='treeholepost',
            index=models.Index(fields=['post_type'], name='treehole_tr_post_ty_5ba403_idx'),
        ),
        migrations.AddIndex(
            model_name='treeholelike',
            index=models.Index(fields=['user'], name='treehole_tr_user_id_2aa739_idx'),
        ),
        migrations.AddIndex(
            model_name='treeholelike',
            index=models.Index(fields=['post'], name='treehole_tr_post_id_1a51bd_idx'),
        ),
        migrations.AddIndex(
            model_name='treeholelike',
            index=models.Index(fields=['comment'], name='treehole_tr_comment_f1ddf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='treeholelike',
            unique_together={('user', 'post'), ('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='treeholecomment',
            index=models.Index(fields=['post', 'created_at'], name='treehole_tr_post_id_bf464a_idx'),
        ),
        migrations.AddIndex(
            model_name='treeholecomment',
            index=models.Index(fields=['author'], name='treehole_tr_author__c1d09b_idx'),
        ),
    ]
