# Generated by Django 4.2.27 on 2025-12-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treehole', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='treeholelike',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='treeholelike',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', True), ('post__isnull', False)), fields=('user', 'post'), name='unique_user_post_like'),
        ),
        migrations.AddConstraint(
            model_name='treeholelike',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False), ('post__isnull', True)), fields=('user', 'comment'), name='unique_user_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='treeholelike',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='like_post_or_comment_only'),
        ),
    ]
