# Generated by Django 4.2.27 on 2025-12-09 08:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('department', models.CharField(max_length=100, verbose_name='所属学院/部门')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='职称')),
                ('courses', models.TextField(blank=True, verbose_name='主讲课程')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='照片')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='办公室')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'ordering': ['department', 'name'],
                'indexes': [models.Index(fields=['department'], name='ratings_tea_departm_c424c1_idx'), models.Index(fields=['name'], name='ratings_tea_name_2e2f21_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
                ('category', models.CharField(choices=[('TEACHER', '教师'), ('CANTEEN', '食堂')], max_length=10, verbose_name='分类')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='颜色')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评论')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='有用数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tags', models.ManyToManyField(blank=True, related_name='ratings', to='ratings.tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpfulMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='ratings.rating', verbose_name='评价')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '有用标记',
                'verbose_name_plural': '有用标记',
            },
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('canteen_building', models.CharField(max_length=50, verbose_name='所属食堂')),
                ('location', models.CharField(max_length=100, verbose_name='位置/楼层')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('specialties', models.TextField(blank=True, verbose_name='特色菜品')),
                ('image', models.ImageField(blank=True, null=True, upload_to='canteen/', verbose_name='照片')),
                ('price_range', models.CharField(blank=True, max_length=50, verbose_name='价格区间')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='营业时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '食堂窗口',
                'verbose_name_plural': '食堂窗口',
                'ordering': ['canteen_building', 'name'],
                'indexes': [models.Index(fields=['canteen_building'], name='ratings_can_canteen_45527e_idx'), models.Index(fields=['name'], name='ratings_can_name_0b7335_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['content_type', 'object_id'], name='ratings_rat_content_35c683_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='ratings_rat_user_id_161600_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['-created_at'], name='ratings_rat_created_c12086_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='helpfulmark',
            index=models.Index(fields=['rating'], name='ratings_hel_rating__925c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='helpfulmark',
            index=models.Index(fields=['user'], name='ratings_hel_user_id_38bdc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helpfulmark',
            unique_together={('user', 'rating')},
        ),
    ]
