# Generated by Django 4.2.27 on 2025-12-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('UNDERGRAD', '本科生'), ('POSTGRAD', '研究生'), ('TEACHER', '教职工'), ('ALUMNI', '校友')], max_length=20, verbose_name='身份类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='学号/工号'),
        ),
    ]
